src/prosepal/accounts/forms.py
from flask_wtf import FlaskForm
from markupsafe import Markup
from wtforms import (
    BooleanField,
    DateField,
    EmailField,
    IntegerRangeField,
    PasswordField,
    StringField,
    SubmitField,
)
from wtforms.validators import (
    DataRequired,
    Email,
    Length,
    NumberRange,
    Optional,
)


def value_or_none(form, field):
    return field.data or None


class SignupForm(FlaskForm):
    email = EmailField(
        "Email",
        validators=[DataRequired(), Email(), Length(min=6, max=40)],
        render_kw={"aria-label": "Email address", "autocomplete": "email"},
    )
    password = PasswordField(
        "Password",
        validators=[DataRequired(), Length(min=6, max=25)],
        render_kw={"aria-label": "Password", "autocomplete": "new-password"},
    )
    terms_agreement = BooleanField(
        Markup(
            "I agree to the <a href='/terms' target='_blank'>"
            "terms and conditions</a>"
        ),
        validators=[DataRequired()],
        render_kw={"aria-label": "Agree to terms and conditions"},
    )
    submit = SubmitField("Signup", render_kw={"aria-label": "Sign up"})

    def validate(self, extra_validators=None):
        initial_validation = super().validate(extra_validators)
        if not initial_validation:
            return False
        return True


class LoginForm(FlaskForm):
    email = EmailField(
        "Email",
        validators=[DataRequired(), Email()],
        render_kw={"aria-label": "Email address", "autocomplete": "email"},
    )
    password = PasswordField(
        "Password",
        validators=[DataRequired()],
        render_kw={
            "aria-label": "Password",
            "autocomplete": "current-password",
        },
    )
    submit = SubmitField("Login", render_kw={"aria-label": "Log in"})


class ForgotPasswordForm(FlaskForm):
    email = EmailField(
        Markup(
            "Enter the email address you signed up with<br \\>"
            "and you will receive a link to reset your<br \\>password"
        ),
        validators=[DataRequired(), Email()],
        render_kw={
            "aria-label": "Enter email address",
            "autocomplete": "email",
        },
    )
    submit = SubmitField(
        "Reset Password",
        render_kw={"aria-label": "Request reset password link"},
    )


class AccountManagementForm(FlaskForm):
    email = EmailField(
        "Email address:",
        validators=[DataRequired(), Email()],
        render_kw={
            "aria-label": "Update email address",
            "auto-complete": "email",
        },
    )
    first_name = StringField(
        "First name:",
        validators=[Optional()],
        render_kw={"aria-label": "First name", "autocomplete": "given-name"},
    )
    last_name = StringField(
        "Last name:",
        validators=[Optional()],
        render_kw={"aria-label": "First name", "autocomplete": "family-name"},
    )
    b_day = DateField(
        "Birthdate:",
        validators=[Optional()],
        render_kw={
            "aria-label": "Birthdate, format YYYY-MM-DD",
            "autocomplete": "bday",
        },
    )
    submit_account = SubmitField("Update Account")


class UpdatePasswordForm(FlaskForm):
    new_password = PasswordField(
        "New Password:",
        validators=[DataRequired()],
        render_kw={
            "aria-label": "New Password",
            "autocomplete": "new-password",
        },
    )
    submit_password = SubmitField(
        "Update Password", render_kw={"aria-label": "Update password"}
    )


class BuyCreditsForm(FlaskForm):
    credits = IntegerRangeField(
        "Credits:",
        validators=[DataRequired(), NumberRange(min=1, max=10)],
        render_kw={"aria-label": "Credits to buy"},
        default=1,
    )
    submit = SubmitField(
        "Buy Credits", render_kw={"aria-label": "Buy credits"}
    )

src/prosepal/accounts/views.py
from flask import (
    Blueprint,
    current_app,
    flash,
    g,
    jsonify,
    redirect,
    render_template,
    request,
    session,
    url_for,
)
from supabase import SupabaseAuth

from .forms import (
    AccountManagementForm,
    BuyCreditsForm,
    ForgotPasswordForm,
    LoginForm,
    SignupForm,
    UpdatePasswordForm,
)
from .utils import (
    get_binders,
    initialize_user_db,
    preload_account_management_form,
    redirect_after_login,
    update_email,
    update_user_details,
)

from prosepal.decorators import login_required
from prosepal.utils import supabase_client, update_db

accounts_app = Blueprint("accounts", __name__)

auth = None


def get_auth_client() -> SupabaseAuth:
    if not g.supabase_client:
        supabase_client()
    global auth
    if auth is None:
        auth = SupabaseAuth(g.supabase_client)
    return auth


@accounts_app.route("/signup", methods=["GET", "POST"])
def signup_view():
    auth = get_auth_client()
    form = SignupForm()
    if form.validate_on_submit():
        email = form.email.data
        try:
            res = auth.sign_up(email=email, password=form.password.data)
            auth_id = res.user.id
            session["user_details"]["auth_id"] = auth_id
            flash(
                "Signup successful."
                "Please check your email to verify your account."
            )
        except Exception as e:
            current_app.logger.error("Unexpected error: %s", str(e))
            flash(e.message)
        if not initialize_user_db():
            current_app.logger.error(f"User row not created for {auth_id}")
    return render_template("accounts/signup.html", form=form)


@accounts_app.route("/login", methods=["GET", "POST"])
def login_view():
    auth = get_auth_client()
    if "access_token" in session and "user_details" in session:
        auth_id = session["user_details"]["auth_id"]
        redirect_after_login(auth_id)
    else:
        auth_id = None
    form = LoginForm()
    if form.validate_on_submit():
        try:
            data = auth.sign_in(
                email=form.email.data, password=form.password.data
            )
            access_token = data.session.access_token
            auth_id = data.user.id
            session["access_token"] = access_token
        except Exception as e:
            current_app.logger.error(f"Unexpected error: {e}")
            flash(str(e))

        redirect_str = redirect_after_login(auth_id)
        return redirect(url_for(redirect_str))

    return render_template("accounts/login.html", form=form)


@accounts_app.route("/logout", methods=["GET"])
@login_required
def logout_view():
    auth = get_auth_client()
    session.pop("user_details", None)
    session.pop("access_token", None)
    session.pop("_flashes", None)
    auth.sign_out()
    return redirect(url_for("accounts.login_view"))


@accounts_app.route("/forgot-password", methods=["GET", "POST"])
def forgot_password_view():
    auth = get_auth_client()
    DOMAIN = current_app.config["DOMAIN"]
    form = ForgotPasswordForm()
    if form.validate_on_submit():
        email = form.email.data
        auth.reset_password(email=email, domain=DOMAIN)
        flash(
            "An email with instructions to reset your password has been sent",
            "message",
        )
    return render_template("accounts/forgot-password.html", form=form)


@accounts_app.route("/reset-password", methods=["GET", "POST"])
def reset_password_view():
    auth = get_auth_client()
    access_token = request.args.get("access_token", "")
    if not access_token:
        return redirect(url_for("login_view"))
    form = UpdatePasswordForm()
    if form.validate_on_submit():
        new_password = form.new_password.data
        try:
            auth.update_user({"password": new_password})
            flash("Password successfully updated.", "message")
        except Exception as e:
            current_app.logger.error("Unexpected error: %s", str(e))
            flash(
                "There was a problem updating your password. "
                "Please try again.",
                "error",
            )

    return render_template("accounts/reset-password.html", form=form)


@accounts_app.route("/account", methods=["GET"])
@login_required
def account_view(section="profile"):
    account_form = preload_account_management_form()
    password_form = UpdatePasswordForm()
    buy_credits_form = BuyCreditsForm()
    binders = get_binders()

    return render_template(
        "accounts/account.html",
        section=section,
        account_form=account_form,
        password_form=password_form,
        binders=binders,
        buy_credits_form=buy_credits_form,
    )


@accounts_app.route("/profile", methods=["GET", "POST"])
@login_required
def profile_view():
    if request.method == "GET":
        return redirect(url_for("accounts.account_view", section="profile"))
    account_form = AccountManagementForm()
    password_form = UpdatePasswordForm()
    auth = get_auth_client()
    if account_form.is_submitted():
        if account_form.validate_on_submit():
            email = account_form.email.data
            user_data = {
                "f_name": account_form.first_name.data or "",
                "l_name": account_form.last_name.data or "",
                "b_day": account_form.b_day.data or "",
            }
            update_email(email, auth)
            update_user_details(user_data)

            if response := update_db():
                flash("Your profile has been updated.", "message")
            else:
                flash("There was an error updating your profile.", "error")
        else:
            print(account_form.errors)
            for field, errors in account_form.errors.items():
                for error in errors:
                    label = getattr(account_form, field).label.text
                    flash(f"Error in the {label}: {error}", "error")

    if password_form.validate_on_submit():
        new_password = password_form.new_password.data
        try:
            response = auth.update_user({"password": new_password})
            access_token = response.access_token
            session["access_token"] = access_token
            flash("Password successfully updated.", "message")
        except Exception as e:
            current_app.logger.error("Unexpected error: %s", str(e))
            flash(
                "There was a problem updating your password. "
                "Please try again.",
                "error",
            )
    return redirect(url_for("accounts.account_view", section="profile"))


@accounts_app.route("/view-binders", methods=["GET"])
@login_required
def view_binders_view():
    return redirect(url_for("accounts.account_view", section="view-binders"))


@accounts_app.route("/buy-credits", methods=["GET", "POST"])
@login_required
def buy_credits_view():
    if request.method == "GET":
        return redirect(
            url_for("accounts.account_view", section="buy-credits")
        )
    form = BuyCreditsForm()
    if form.validate_on_submit():
        num_credits = form.credits.data
        return redirect(
            url_for("stripe.checkout_view", num_credits=num_credits)
        )


@accounts_app.route("/sort-binders", methods=["POST"])
@login_required
def sort_binders_view():
    data = request.get_json()
    column = data.get("column")
    sort_descending = data.get("sort_descending", False)
    binders_list = session.get("binders_list", "")

    binders = sorted(
        binders_list, key=lambda x: x[column], reverse=sort_descending
    )
    return jsonify(binders)

src/prosepal/binders/views.py
from flask import Blueprint, jsonify, render_template, session

from .forms import LoreBinderForm
from .utils import start_binder, str_to_dedup_list

from prosepal.decorators import credit_required, login_required
from prosepal.file_handling import send_file_to_bucket

binders_app = Blueprint("binders", __name__)


@binders_app.route("/lorebinder", methods=["GET", "POST"])
@login_required
@credit_required
def lorebinder_form_view():
    user_folder = session["user_details"]["auth_id"]
    user_email = session["user_details"]["email"]
    form = LoreBinderForm()
    if form.validate_on_submit():
        file = form.file_upload.data
        upload_path = send_file_to_bucket(user_folder, file, bucket="binders")

        title = form.title.data
        author = form.author.data
        narrator = form.narrator.data
        character_attributes_str = form.character_attributes.data
        other_attributes_str = form.other_attributes.data

        character_attributes = str_to_dedup_list(character_attributes_str)
        other_attributes = str_to_dedup_list(other_attributes_str)

        api_payload = {
            "upload_path": upload_path,
            "title": title,
            "author": author,
            "narrator": narrator,
            "character_attributes": character_attributes,
            "other_attributes": other_attributes,
            "email": user_email,
        }

        response = start_binder(api_payload, endpoint_name="lorebinder")

        if response:
            message = (
                "Your Lorebinder has been started. "
                "You should receive an email within the next hour."
            )
            status = "success"
        else:
            message = (
                "There was a problem starting your Lorebinder. "
                "An administrator has been contacted."
            )
            status = "warning"
        return jsonify({"message": message, "status": status})

    return render_template("binders/lorebinder.html", form=form)

src/prosepal/templates/accounts/account-sidebar.html
  <div class="sidebar">
    <div class="sidebar-nav">
      <button class="sidebar-item {% if section == 'profile' %}active{% endif %}">
        <a href="{{ url_for('accounts.account_view', section='profile') }}" title="Profile">Profile</a>
      </button>
      <button class="sidebar-item {% if section == 'view-binders' %}active{% endif %}">
        <a href="{{ url_for('accounts.account_view', section='view-binders') }}" title="View Past Binders">View Binders</a>
      </button>
      <button class="sidebar-item {% if section == 'buy-credits' %}active{% endif %}">
        <a href="{{ url_for('accounts.account_view', section='buy-credits') }}" title="Buy credits">Buy Credits</a>
      </button>
    </div>
  </div>

src/prosepal/templates/accounts/account.html
{% extends 'password-base.html' %}

{% block title %}Account Management{% endblock %}

{% block extra_css %}
  {{ super() }}
  <link rel="stylesheet" href="{{ url_for('static', filename='css/account.css') }}">
{% endblock %}

{% block extra_js %}
  {{ super() }}
  <script src="{{ url_for('static', filename='js/viewBinder.js')}}"></script>
{% endblock %}

{% block content %}
  {% if section == 'profile' %}
  <h1 class="account-header">Profile</h1>
  {% include 'accounts/account-sidebar.html' %}
  <div data-section="profile" id="profile">
    {% include 'accounts/profile.html' %}
  </div>
{% endif %}

{% if section == 'view-binders' %}
<h1 class="account-header">View Purchased LoreBinders</h1>
  <div data-section="view-binders" id="binder-view">
    {% include 'accounts/account-sidebar.html' %}
    {% include 'accounts/view-binders.html' %}
  </div>
{% endif %}

{% if section == 'buy-credits' %}
<h1 class="account-header">Buy Credits</h1>
  <div data-section="buy-credits" id="credit-slider">
    {% include 'accounts/account-sidebar.html' %}
    {% include 'accounts/buy-credits.html' %}
  </div>
{% endif %}

{% endblock %}

{% block end_js %}
  <script src="{{ url_for('static', filename='js/purchase-slider.js')}}"></script>
{% endblock %}

src/prosepal/templates/accounts/buy-credits.html
{% block content %}
<div class="slider-container">
  <form method="POST" class="form box" id="credit-slider" action="{{ url_for('accounts.buy_credits_view') }}">
    {{ buy_credits_form.hidden_tag() }}
    <h3>Credits:  <span class="h3-num" id="credits-num">1</span></h3>
    {{ buy_credits_form.credits }}
    <h3>Price: $<span class="h3-num" id="price-num">10</span></h3>
    {{ buy_credits_form.submit(class="btn btn-primary") }}
  </form>
</div>

{% endblock %}

src/prosepal/templates/accounts/forgot-password.html
{% extends 'forms-base.html' %}
{% block title %}Forgot Password{% endblock %}

{% block content %}
<h1>Reset password</h1>
  {% with messages = get_flashed_messages() %}
    {% if messages %}

  <div class="flash-modal">
        <span class="material-symbols-outlined close-icon">
          close
          </span>
        <ul class="flashes">
        {% for message in messages %}
        <li>{{ message }}</li>
        {% endfor %}
        </ul>
      </div>
    {% endif %}
  {% endwith %}
<form method="POST" class="form box" enctype="multipart/form-data">
  {{ form.csrf_token }}
  <div class="forgot-email-container">
    {{ form.email.label(class_="forgot-email-label") }}
    {{ form.email(class_="forgot-email-input") }}
    {% if form.email.errors %}
      {% for error in form.email.errors %}
        <div class="error">{{ error }}</div>
      {% endfor %}
    {% endif %}

  </div>
  <input type="submit" value="Reset password" class="btn btn-primary">
{% endblock %}

src/prosepal/templates/accounts/login.html
{% extends "password-base.html" %}

{% block title %}Login{% endblock %}


{% block content %}
    <div class="form box">
      {% with messages = get_flashed_messages() %}
      {% if messages %}

  <div class="flash-modal">
          <span class="material-symbols-outlined close-icon">
            close
            </span>
          <ul class="flashes">
          {% for message in messages %}
          <li>{{ message }}</li>
          {% endfor %}
          </ul>
        </div>
      {% endif %}
    {% endwith %}
        <form id="login-form" class="form" method="post" action="{{ url_for('accounts.login_view') }}">
            {{ form.hidden_tag() }}
            <h1 class="content-title">Login</h1>
            <div class="input-boxes">
                <!-- Email Field -->
                <div class="flex-form" id="div-id_email">
                    {{ form.email.label(class="input-label") }}
                    {{ form.email(size=30, class="input-box", id="id_email") }}
                    {% if form.email.description %}
                        <small class="help-text">{{ form.email.description }}</small>
                    {% endif %}
                    {% if form.email.errors %}
                        {% for error in form.email.errors %}
                            <div class="error">{{ error }}</div>
                        {% endfor %}
                    {% endif %}
                </div>
                <!-- Password Field -->
                <div class="flex-form" id="div-id_password">
                    {{ form.password.label(class="input-label") }}
                    <div class="password-container">
                        {{ form.password(size=30, class="input-box", id="id_password") }}
                        <span class="material-symbols-outlined" id="eye">visibility</span>
                    </div>
                    {% if form.password.description %}
                        <small class="help-text">{{ form.password.description }}</small>
                    {% endif %}
                    {% if form.password.errors %}
                        {% for error in form.password.errors %}
                            <div class="error">{{ error }}</div>
                        {% endfor %}
                    {% endif %}
                </div>
            </div>
            {{ form.submit(class="btn btn-primary")}}
        </form>
        <div class="forgot-password">
          <p><a href="{{ url_for('accounts.forgot_password_view')}}" title="Forgot password">Forgot password?</a></p>
        </div>
        <div class="switch-auth">
            Don't have an account? <a href="{{ url_for('accounts.signup_view') }}" id="signup-link" class="auth-switch-link">Sign Up</a>
        </div>
    </div>
{% endblock content %}

src/prosepal/templates/accounts/profile.html
{% block content %}
{% with messages = get_flashed_messages() %}
{% if messages %}

  <div class="flash-modal">
    <span class="material-symbols-outlined close-icon">
      close
      </span>
    <ul class="flashes">
    {% for message in messages %}
    <li>{{ message }}</li>
    {% endfor %}
    </ul>
  </div>
{% endif %}
{% endwith %}
    <h2>Update Profile</h2>
    <div class="form-grid" id="div-id_account">

    <form method="post" class="box" id="account-management-form" action="{{ url_for('accounts.profile_view') }}">
        {{ account_form.hidden_tag() }}
        <div class="flex-form">
            {{ account_form.email.label(class="input-label") }}
            {{ account_form.email(size=20) }}
            {% if account_form.email.errors %}
              <ul class="error">
                {% for error in account_form.email.errors %}
                  <li>{{ error }}</li>
                {% endfor %}
              </ul>
            {% endif %}
        </div>
        <div class="flex-form">
            {{ account_form.first_name.label(class="input-label") }}
            {{ account_form.first_name(size=20) }}
            {% if account_form.first_name.errors %}
              <ul class="error">
                {% for error in account_form.first_name.errors %}
                  <li>{{ error }}</li>
                {% endfor %}
              </ul>
            {% endif %}
        </div>
        <div class="flex-form">
            {{ account_form.last_name.label(class="input-label") }}
            {{ account_form.last_name(size=20) }}
            {% if account_form.last_name.errors %}
              <ul class="error">
                {% for error in account_form.last_name.errors %}
                  <li>{{ error }}</li>
                {% endfor %}
              </ul>
            {% endif %}
        </div>
        <div class="flex-form">
            {{ account_form.b_day.label(class="input-label") }}
            {{ account_form.b_day(size=20) }}
            {% if account_form.b_day.errors %}
              <ul class="error">
                {% for error in account_form.b_day.errors %}
                  <li>{{ error }}</li>
                {% endfor %}
              </ul>
            {% endif %}
        </div>
        {{ account_form.submit_account(class="btn btn-primary")}}
    </form>
    </div>
    <div class="form-grid" id="credit-info">
      <div class="box" id="credit-info-inner">
        <h2>Credit Balance: {{ user.credits_available }}</h2>
        <h2>Credits Used: {{ user.credits_used }}</h2>
      </div>
    </div>
    <!-- Password Field -->
    <div class="form-grid" id="div-id_password">

        <form method="POST" class="box" id="update-password-form" action="{{ url_for('accounts.profile_view') }}">
          <h2>Update Password</h2>
          {{ password_form.hidden_tag() }}
          <div class="flex-form" id="div-id_password">
          {{ password_form.new_password.label(class="input-label") }}
          <div class="password-container">
              {{ password_form.new_password(size=30, class="input-box", id="id_password") }}
              <span class="material-symbols-outlined" id="eye">visibility</span>
          </div>
          {% if password_form.new_password.description %}
              <small class="help-text">{{ password_form.new_password.description }}</small>
          {% endif %}
          {% if password_form.new_password.errors %}
              {% for error in password_form.new_password.errors %}
                  <div class="error">{{ error }}</div>
              {% endfor %}
          {% endif %}
          </div>
          {{ password_form.submit_password(class="btn btn-primary")}}
        </form>
    </div>
{% endblock content %}

src/prosepal/templates/accounts/reset-password.html
{% extends 'password-base.html' %}
{% block title %}Forgot Password{% endblock %}


{% block content %}
<h1>Reset password</h1>
{% with messages = get_flashed_messages() %}
{% if messages %}

  <div class="flash-modal">
    <span class="material-symbols-outlined close-icon">
      close
      </span>
    <ul class="flashes">
    {% for message in messages %}
    <li>{{ message }}</li>
    {% endfor %}
    </ul>
  </div>
{% endif %}
{% endwith %}
<form method="POST" class="form box" enctype="multipart/form-data">
  {{ form.hidden_tag() }}
  <!-- Password Field -->
  <div class="flex-form" id="div-id_password">
    {{ form.password.label(class="input-label") }}
    <div class="password-container">
        {{ form.password(size=30, class="input-box", id="id_password") }}
        <span class="material-symbols-outlined" id="eye">visibility</span>
    </div>
    {% if form.password.description %}
        <small class="help-text">{{ form.password.description }}</small>
    {% endif %}
    {% if form.password.errors %}
        {% for error in form.password.errors %}
            <div class="error">{{ error }}</div>
        {% endfor %}
    {% endif %}
    {{ form.submit_password(class="btn btn-primary")}}
</div>
{% endblock %}

src/prosepal/templates/accounts/signup.html
{% extends "password-base.html" %}

{% block title %}Signup{% endblock %}

{% block content %}
    <div class="form box">
      {% with messages = get_flashed_messages() %}
      {% if messages %}

  <div class="flash-modal">
          <span class="material-symbols-outlined close-icon">
            close
            </span>
          <ul class="flashes">
          {% for message in messages %}
          <li>{{ message }}</li>
          {% endfor %}
          </ul>
        </div>
      {% endif %}
    {% endwith %}
        <form class="user-form" method="POST" action="{{ url_for('accounts.signup_view') }}">
            {{ form.hidden_tag() }}
            <h1>Become a Pal to your Prose</h1>
            <div id="required-div">
                <h3 class="required-text">All fields are required.</h3>
            </div>
            <div class="input-boxes">
              <!-- Email Field -->
              <div class="flex-form" id="div-id_email">
                  {{ form.email.label(class="input-label") }}
                  {{ form.email(size=30, class="input-box", id="id_email") }}
                  {% if form.email.description %}
                      <small class="help-text">{{ form.email.description }}</small>
                  {% endif %}
                  {% if form.email.errors %}
                      {% for error in form.email.errors %}
                          <div class="error">{{ error }}</div>
                      {% endfor %}
                  {% endif %}
              </div>
              <!-- Password Field -->
              <div class="flex-form" id="div-id_password">
                  {{ form.password.label(class="input-label") }}
                  <div class="password-container">
                      {{ form.password(size=30, class="input-box", id="id_password") }}
                      <span class="material-symbols-outlined" id="eye">visibility</span>
                  </div>
                  {% if form.password.description %}
                      <small class="help-text">{{ form.password.description }}</small>
                  {% endif %}
                  {% if form.password.errors %}
                      {% for error in form.password.errors %}
                          <div class="error">{{ error }}</div>
                      {% endfor %}
                  {% endif %}
              </div>
            </div>
            <div id="checkboxes">
                <div class="check-grid" id="terms">
                    {{ form.terms_agreement(id=form.terms_agreement.id, class=form.terms_agreement.css_class) }}
                    {{ form.terms_agreement.label(class="user-input-label") }}
                </div>
            </div>
            {{ form.submit(class="btn btn-primary")}}
        </form>
        <div class="switch-auth">
            Already have an account? <a href="{{ url_for('accounts.login_view') }}" id="login-link">Login</a>
        </div>
    </div>
{% endblock %}

src/prosepal/templates/accounts/view-binders.html
{% block content %}
    {% if binders %}
    <div class="binder-table">
      <div class="binder-table-header">
        <span class="binder-label" id="title">
          Title<span class="material-symbols-outlined mini" id="title-sort">sort</span>
        </span>
        <span class="binder-label" id="author">
          Author<span class="material-symbols-outlined mini" id="author-sort">sort</span>
        </span>
        <span class="binder-label" id="created_on">
          Created<span class="material-symbols-outlined mini" id="created_on-sort">swap_vert</span>
        </span>
        <span class="binder-label" id="dl-label">
          Download
        </span>
      </div>
      <ul class="table-rows">
        {% for binder in binders %}
          <li class="binder-row">
            <span class="binder-info" id="title-info">{{ binder.title }}</span>
            <span class="binder-info" id="author-info">{{ binder.author }}</span>
            <span class="binder-info" id="date-info">{{ binder.created_on }}</span>
            <span class="binder-info" id="download-info">
              {% if binder.signed_url != "Please check again later" %}
                <a href="{{ binder.signed_url }}"" target="_blank"><span class="material-symbols-outlined">download</span></a>
              {% else %}
                <span class="material-symbols-outlined">pending</span>
              {% endif %}
            </span>
          </li>
        {% endfor %}
      </ul>
    </div>
    {% else %}
    <div class="box binder-table">
    <p>You have no purchased any LoreBinders yet. <a href="{{ url_for('binders.lorebinder_form_view') }}" title="Start LoreBinder">Get started on your first one now</a></p>
      </div>
  {% endif %}
{% endblock %}