src/prosepal/mailerlite/forms.py
from flask_wtf import FlaskForm
from wtforms import EmailField, SubmitField
from wtforms.validators import DataRequired, Email, Length


class WaitListSignupForm(FlaskForm):
    email = EmailField(
        "Email",
        validators=[DataRequired(), Email(), Length(min=6, max=40)],
        render_kw={
            "aria-label": "Email address",
            "autocomplete": "email",
            "placeholder": "Email",
        },
    )
    submit = SubmitField(
        "Join Waitlist", render_kw={"aria-label": "Join Waitlist"}
    )


class MailerLiteSignupForm(FlaskForm):
    email = EmailField(
        "Email",
        validators=[DataRequired(), Email(), Length(min=6, max=40)],
        render_kw={
            "aria-label": "Email address",
            "autocomplete": "email",
            "placeholder": "Email",
        },
    )
    ubmit = SubmitField("Subscribe", render_kw={"aria-label": "Subscribe"})

src/prosepal/core/views.py
from flask import Blueprint, flash, render_template

from .forms import ContactForm
from .utils import get_update_message, send_message

core_app = Blueprint("core", __name__)


@core_app.route("/")
def landing_page():
    return render_template("core/index.html")


@core_app.route("/privacy")
def privacy_page():
    return render_template("core/privacy.html")


@core_app.route("/terms")
def terms_page():
    return render_template("core/terms.html")


@core_app.route("/contact-us", methods=["GET", "POST"])
def contact_us_view():
    form = ContactForm()

    if form.validate_on_submit():
        name = form.name.data
        user_email = form.email.data
        message = form.message.data
        send_message(name, user_email, message)
        flash("Message sent", "success")

    return render_template("core/contact-us.html", form=form)


@core_app.route("/get-header", methods=["GET"])
def get_header():
    return render_template("core/header.html")


@core_app.route("/get-mobile-header", methods=["GET"])
def get_mobile_header():
    return render_template("core/mobile-header.html")


@core_app.route("/check-update", methods=["GET"])
def check_update_view():
    update_message = get_update_message()
    return render_template("core/updates.html", update_message=update_message)

src/prosepal/mailerlite/views.py
from decouple import config
from flask import Blueprint, redirect, render_template

from .forms import WaitListSignupForm
from .utils import add_subscriber

mailerlite_app = Blueprint("mailerlite", __name__)


@mailerlite_app.route("/ml-join-waitlist", methods=["GET", "POST"])
def waitlist_form_view():
    form = WaitListSignupForm()
    if form.validate_on_submit():
        email = form.email.data
        GROUP_ID: int = config("MAILERLITE_WAITLIST_ID")
        response = add_subscriber(email, groups=[GROUP_ID])
        if response.data:
            return redirect(render_template("mailerlite/ml-success.html"))
        elif response.errors:
            error_message = response.errors.get("email", "Invalid email")[0]
            return render_template(
                "mailerlite/ml-join-waitlist.html",
                form=form,
                error_message=error_message,
            )
        else:
            return render_template(
                "mailerlite/ml-join-waitlist.html", form=form
            )
    return render_template("mailerlite/ml-join-waitlist.html", form=form)


@mailerlite_app.route("/ml-sucess", methods=["GET"])
def ml_success_view():
    return render_template("ml-success.html")

src/prosepal/templates/mailerlite/ml-base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block ml_title%}iframe{% endblock %}</title>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Exo:wght@300;500&family=Open+Sans:ital,wght@0,300..800;1,300..800&family=Raleway:wght@700&family=Share+Tech&family=Share+Tech+Mono&family=Source+Sans+3:ital,wght@0,700;1,700&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0" />
  <link rel="stylesheet" href="{{ url_for('static', filename='css/mailerlite.css') }}">
  <script src="{{ url_for('static', filename='js/mailerlite.js') }}"></script>
</head>
<body>
    {% block ml_container %}

    {% endblock %}
</body>
</html>

src/prosepal/templates/mailerlite/ml-join-waitlist.html
{% extends 'mailerlite/ml-base.html' %}
{% block ml_title%} Join Waitlist iframe{% endblock %}<

{% block ml_container %}
  <div class="ml-subscribe-container">
    <h1>Join the Waitlist</h1>
    {% if error_message %}
      <div class="alert"><span class="material-symbols-outlined" id="error">
        error
        </span><br />
          {{ error_message }}
      </div>
    {% endif %}
    <form id="ml-join-waitlist-form" action="{{ url_for('mailerlite.waitlist_form_view') }}" method="post">
      {{ form.hidden_tag() }}
      {{ form.email.label(class="ml-subscribe-label") }}
      {{ form.email(class="ml-subscribe-input") }}
      {% if form.email.description %}
        <small class="help-text">{{ form.email.description }}</small>
      {% endif %}
      {% if form.email.errors %}
        {% for error in form.email.errors %}
          <div class="error">{{ error }}</div>
        {% endfor %}
      {% endif %}
      {{ form.submit(class="ml-subscribe-button") }}
      <p>You can unsubscribe anytime. For more details, review our <a href="{{url_for("core.privacy_page") }}" target="_blank">Privacy Policy</a>.</p>
    </form>
  </div>
{% endblock %}

src/prosepal/templates/mailerlite/ml-success.html
{% block ml_title %}Success{% endblock %}
{% block ml_container %}
  <p>Thank you.</p>
  <p>You will receive an email shortly to confirm</p>
{% endblock %}