src/prosepal/core/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired, Email


class ContactForm(FlaskForm):
    name = StringField("Your Name", validators=[DataRequired()])
    email = StringField("Your Email", validators=[DataRequired(), Email()])
    message = TextAreaField("Your Message", validators=[DataRequired()])
    submit = SubmitField("Send Message")

src/prosepal/accounts/views.py
from flask import (
    Blueprint,
    current_app,
    flash,
    g,
    jsonify,
    redirect,
    render_template,
    request,
    session,
    url_for,
)
from supabase import SupabaseAuth

from .forms import (
    AccountManagementForm,
    BuyCreditsForm,
    ForgotPasswordForm,
    LoginForm,
    SignupForm,
    UpdatePasswordForm,
)
from .utils import (
    get_binders,
    initialize_user_db,
    preload_account_management_form,
    redirect_after_login,
    update_email,
    update_user_details,
)

from prosepal.decorators import login_required
from prosepal.utils import supabase_client, update_db

accounts_app = Blueprint("accounts", __name__)

auth = None


def get_auth_client() -> SupabaseAuth:
    if not g.supabase_client:
        supabase_client()
    global auth
    if auth is None:
        auth = SupabaseAuth(g.supabase_client)
    return auth


@accounts_app.route("/signup", methods=["GET", "POST"])
def signup_view():
    auth = get_auth_client()
    form = SignupForm()
    if form.validate_on_submit():
        email = form.email.data
        try:
            res = auth.sign_up(email=email, password=form.password.data)
            auth_id = res.user.id
            session["user_details"]["auth_id"] = auth_id
            flash(
                "Signup successful."
                "Please check your email to verify your account."
            )
        except Exception as e:
            current_app.logger.error("Unexpected error: %s", str(e))
            flash(e.message)
        if not initialize_user_db():
            current_app.logger.error(f"User row not created for {auth_id}")
    return render_template("accounts/signup.html", form=form)


@accounts_app.route("/login", methods=["GET", "POST"])
def login_view():
    auth = get_auth_client()
    if "access_token" in session and "user_details" in session:
        auth_id = session["user_details"]["auth_id"]
        redirect_after_login(auth_id)
    else:
        auth_id = None
    form = LoginForm()
    if form.validate_on_submit():
        try:
            data = auth.sign_in(
                email=form.email.data, password=form.password.data
            )
            access_token = data.session.access_token
            auth_id = data.user.id
            session["access_token"] = access_token
        except Exception as e:
            current_app.logger.error(f"Unexpected error: {e}")
            flash(str(e))

        redirect_str = redirect_after_login(auth_id)
        return redirect(url_for(redirect_str))

    return render_template("accounts/login.html", form=form)


@accounts_app.route("/logout", methods=["GET"])
@login_required
def logout_view():
    auth = get_auth_client()
    session.pop("user_details", None)
    session.pop("access_token", None)
    session.pop("_flashes", None)
    auth.sign_out()
    return redirect(url_for("accounts.login_view"))


@accounts_app.route("/forgot-password", methods=["GET", "POST"])
def forgot_password_view():
    auth = get_auth_client()
    DOMAIN = current_app.config["DOMAIN"]
    form = ForgotPasswordForm()
    if form.validate_on_submit():
        email = form.email.data
        auth.reset_password(email=email, domain=DOMAIN)
        flash(
            "An email with instructions to reset your password has been sent",
            "message",
        )
    return render_template("accounts/forgot-password.html", form=form)


@accounts_app.route("/reset-password", methods=["GET", "POST"])
def reset_password_view():
    auth = get_auth_client()
    access_token = request.args.get("access_token", "")
    if not access_token:
        return redirect(url_for("login_view"))
    form = UpdatePasswordForm()
    if form.validate_on_submit():
        new_password = form.new_password.data
        try:
            auth.update_user({"password": new_password})
            flash("Password successfully updated.", "message")
        except Exception as e:
            current_app.logger.error("Unexpected error: %s", str(e))
            flash(
                "There was a problem updating your password. "
                "Please try again.",
                "error",
            )

    return render_template("accounts/reset-password.html", form=form)


@accounts_app.route("/account", methods=["GET"])
@login_required
def account_view(section="profile"):
    account_form = preload_account_management_form()
    password_form = UpdatePasswordForm()
    buy_credits_form = BuyCreditsForm()
    binders = get_binders()

    return render_template(
        "accounts/account.html",
        section=section,
        account_form=account_form,
        password_form=password_form,
        binders=binders,
        buy_credits_form=buy_credits_form,
    )


@accounts_app.route("/profile", methods=["GET", "POST"])
@login_required
def profile_view():
    if request.method == "GET":
        return redirect(url_for("accounts.account_view", section="profile"))
    account_form = AccountManagementForm()
    password_form = UpdatePasswordForm()
    auth = get_auth_client()
    if account_form.is_submitted():
        if account_form.validate_on_submit():
            email = account_form.email.data
            user_data = {
                "f_name": account_form.first_name.data or "",
                "l_name": account_form.last_name.data or "",
                "b_day": account_form.b_day.data or "",
            }
            update_email(email, auth)
            update_user_details(user_data)

            if response := update_db():
                flash("Your profile has been updated.", "message")
            else:
                flash("There was an error updating your profile.", "error")
        else:
            print(account_form.errors)
            for field, errors in account_form.errors.items():
                for error in errors:
                    label = getattr(account_form, field).label.text
                    flash(f"Error in the {label}: {error}", "error")

    if password_form.validate_on_submit():
        new_password = password_form.new_password.data
        try:
            response = auth.update_user({"password": new_password})
            access_token = response.access_token
            session["access_token"] = access_token
            flash("Password successfully updated.", "message")
        except Exception as e:
            current_app.logger.error("Unexpected error: %s", str(e))
            flash(
                "There was a problem updating your password. "
                "Please try again.",
                "error",
            )
    return redirect(url_for("accounts.account_view", section="profile"))


@accounts_app.route("/view-binders", methods=["GET"])
@login_required
def view_binders_view():
    return redirect(url_for("accounts.account_view", section="view-binders"))


@accounts_app.route("/buy-credits", methods=["GET", "POST"])
@login_required
def buy_credits_view():
    if request.method == "GET":
        return redirect(
            url_for("accounts.account_view", section="buy-credits")
        )
    form = BuyCreditsForm()
    if form.validate_on_submit():
        num_credits = form.credits.data
        return redirect(
            url_for("stripe.checkout_view", num_credits=num_credits)
        )


@accounts_app.route("/sort-binders", methods=["POST"])
@login_required
def sort_binders_view():
    data = request.get_json()
    column = data.get("column")
    sort_descending = data.get("sort_descending", False)
    binders_list = session.get("binders_list", "")

    binders = sorted(
        binders_list, key=lambda x: x[column], reverse=sort_descending
    )
    return jsonify(binders)

src/prosepal/binders/views.py
from flask import Blueprint, jsonify, render_template, session

from .forms import LoreBinderForm
from .utils import start_binder, str_to_dedup_list

from prosepal.decorators import credit_required, login_required
from prosepal.file_handling import send_file_to_bucket

binders_app = Blueprint("binders", __name__)


@binders_app.route("/lorebinder", methods=["GET", "POST"])
@login_required
@credit_required
def lorebinder_form_view():
    user_folder = session["user_details"]["auth_id"]
    user_email = session["user_details"]["email"]
    form = LoreBinderForm()
    if form.validate_on_submit():
        file = form.file_upload.data
        upload_path = send_file_to_bucket(user_folder, file, bucket="binders")

        title = form.title.data
        author = form.author.data
        narrator = form.narrator.data
        character_attributes_str = form.character_attributes.data
        other_attributes_str = form.other_attributes.data

        character_attributes = str_to_dedup_list(character_attributes_str)
        other_attributes = str_to_dedup_list(other_attributes_str)

        api_payload = {
            "upload_path": upload_path,
            "title": title,
            "author": author,
            "narrator": narrator,
            "character_attributes": character_attributes,
            "other_attributes": other_attributes,
            "email": user_email,
        }

        response = start_binder(api_payload, endpoint_name="lorebinder")

        if response:
            message = (
                "Your Lorebinder has been started. "
                "You should receive an email within the next hour."
            )
            status = "success"
        else:
            message = (
                "There was a problem starting your Lorebinder. "
                "An administrator has been contacted."
            )
            status = "warning"
        return jsonify({"message": message, "status": status})

    return render_template("binders/lorebinder.html", form=form)

src/prosepal/core/views.py
from flask import Blueprint, flash, render_template

from .forms import ContactForm
from .utils import get_update_message, send_message

core_app = Blueprint("core", __name__)


@core_app.route("/")
def landing_page():
    return render_template("core/index.html")


@core_app.route("/privacy")
def privacy_page():
    return render_template("core/privacy.html")


@core_app.route("/terms")
def terms_page():
    return render_template("core/terms.html")


@core_app.route("/contact-us", methods=["GET", "POST"])
def contact_us_view():
    form = ContactForm()

    if form.validate_on_submit():
        name = form.name.data
        user_email = form.email.data
        message = form.message.data
        send_message(name, user_email, message)
        flash("Message sent", "success")

    return render_template("core/contact-us.html", form=form)


@core_app.route("/get-header", methods=["GET"])
def get_header():
    return render_template("core/header.html")


@core_app.route("/get-mobile-header", methods=["GET"])
def get_mobile_header():
    return render_template("core/mobile-header.html")


@core_app.route("/check-update", methods=["GET"])
def check_update_view():
    update_message = get_update_message()
    return render_template("core/updates.html", update_message=update_message)

src/prosepal/free/views.py
from pathlib import Path

from flask import Blueprint, jsonify, render_template, request, send_file

# from prosepal.exceptions import APIError
from prosepal.free import utils

from .controller import (
    process_convert_ebook_submission,
    process_finetune_submission,
)
from .forms import EbookConversionForm, FineTuneForm, JSONLConversionForm

free_app = Blueprint("free", __name__)


def training_status():
    pass  # dummy function till API is implemented


@free_app.route("/create-jsonl", methods=["GET", "POST"])
def create_jsonl():
    form = JSONLConversionForm()
    if form.validate_on_submit():
        if uploaded_file := form.csv.data:
            filename: str = Path(uploaded_file.filename).stem
            return_file = utils.call_jsonl_api(uploaded_file)
            return send_file(
                return_file,
                as_attachment=True,
                download_name=f"{filename}.jsonl",
                mimetype="application/octet-stream",
            )
    return render_template("free/create-jsonl.html", form=form)


@free_app.route("/convert-ebook", methods=["GET", "POST"])
def convert_ebook():
    form = EbookConversionForm()
    if form.validate_on_submit():
        book_name, download_path = process_convert_ebook_submission(form)
        return send_file(
            path_or_file=download_path,
            as_attachment="True",
            download_name=book_name,
        )

    return render_template("free/convert-ebook.html", form=form)


@free_app.route("/finetune", methods=["GET", "POST"])
def finetune():
    form = FineTuneForm()
    if form.validate_on_submit():
        return process_finetune_submission(form)
    return render_template("free/finetune.html", form=form)


@free_app.route("/status", methods=["POST"])
def status():
    data = request.get_json()
    user_folder = data.get("user_folder")
    return jsonify({"status": training_status.get(user_folder, "Not started")})


@free_app.route("/finetune/instructions", methods=["GET"])
def finetune_instructions():
    return render_template("free/instructions.html")


@free_app.route("/free", methods=["GET"])
def free_page():
    return render_template("free/free.html")

src/prosepal/templates/core/contact-us.html
{% extends 'forms-base.html' %}

{% block title %}Contact Us{% endblock %}
{% block extra_js %}
  <script src="{% static, 'js/invalid-input.js'}"></script>
{% endblock extra_js}
{% block content %}
  <h1>Contact Us</h1>
  <p>Please fill out the form below and we will get back to you as soon as possible.</p>

  {% if form.errors %}
  <div class="alert alert-danger" role="alert" aria-live="polite">
    Please correct the errors below.
  </div>
  {% endif %}
  {% with messages = get_flashed_messages() %}
    {% if messages %}

  <div class="flash-modal">
        <span class="material-symbols-outlined close-icon">
          close
          </span>
        <ul class="flashes">
        {% for message in messages %}
        <li>{{ message }}</li>
        {% endfor %}
        </ul>
      </div>
    {% endif %}
  {% endwith %}
  <form class="contact-form form box" method="post" action="{{ url_for('core.contact_us_view') }}">
    {{ form.hidden_tag() }}
    {{ form.name.label(class="input-label") }}
    {{ form.name(class="input-box") }}
    {{ form.email.label(class="input-label") }}
    {{ form.email(class="input-box") }}
    {{ form.message.label(class="input-label") }}
    {{ form.message }}
    {{ form.submit(class="btn btn-primary")}}
  </form>
{% endblock content %}

src/prosepal/templates/core/header.html
<header>
  <nav class="header-nav">
    <ul class="header-menu">
      <li class="logo"><a href="{{ url_for('core.landing_page') }}" title="homepage">
        <img src="{{ url_for('static', filename='images/logo.png') }}" alt="ProsePal logo" id="logo">
      </a></li>
      <li class="header-list"><a href="{{ url_for('binders.lorebinder_form_view') if g.user else url_for('core.landing_page') }}">LoreBinders</a></li>
      <li class="dropdown header-list"><a href="{{ url_for('free.free_page') }}">Free Tools</a>
        <ul class="dropdown-content">
          <li class="dropdown-item"><a href="{{ url_for('free.finetune') }}">GPT 3.5 Finetuner</a></li>
          <li class="dropdown-item sub"><a href="{{ url_for('free.finetune_instructions') }}">Instructions</a></li>
          <li class="dropdown-item"><a href="{{ url_for('free.convert_ebook') }}">Convert-ebook</a></li>
        </ul>
      </li>
      {% if g.user %}
        <li class="dropdown header-right" id="account"><a href="{{ url_for('accounts.profile_view') }}">Account</a>
          <ul class="dropdown-content last">
            <li class="dropdown-item account"><a href="{{ url_for('accounts.profile_view') }}">Profile</a></li>
            <li class="dropdown-item account"><a href="{{ url_for('accounts.buy_credits_view') }}">Buy Credits</a></li>
            <li class="dropdown-item account"><a href="{{ url_for('accounts.view_binders_view') }}">Past Purchases</a></li>
            <li class="credit-item"><p class="credits">Credits: {{ g.user.credits_available }}</p></li>
            <li class="dropdown-item account"><a href="{{ url_for('accounts.logout_view') }}">Logout</a></li>
          </ul>
        </li>
      {% else %}
        <li class="header-list header-right"><a href="{{ url_for('accounts.signup_view') }}">Sign Up</a></li>
        <li class="header-list header-right"><a href="{{ url_for('accounts.login_view') }}">Log In</a></li>
      {% endif %}
      <li class="header-right toggle">
        <div id="toggle">
          <p class="shown" id="toggleLabel">Light mode</p>
          <label class="switch">
            <input type="checkbox" id="darkModeToggle" aria-label="Enable dark mode">
            <span class="slider round"></span>
          </label>
          <p class="hidden" id="toggleLabelDark">Dark mode</p>
        </div>
      </li>
    </ul>
  </nav>
</header>

src/prosepal/templates/core/mobile-header.html
<header>
  <nav class="header-nav">
    <div class="tab first" id="lorebinder">
      <a href="{{ url_for('binders.lorebinder_form_view') if g.user else url_for('core.landing_page') }}" title="Start LoreBinder">
        <span class="material-symbols-outlined">auto_stories</span>
        <h6>Lorebinder</h6>
      </a>
    </div>
    <div class="tab" id="free">
    <a href="{{ url_for('free.free_page') }}" title="Free tools">
      <span class="material-symbols-outlined">featured_seasonal_and_gifts</span>
      <h6>Free tools</h6>
    </a>
    </div>
    <div class="tab" id="mobile-toggle">
      <span class="material-symbols-outlined" id="darkModeToggle" aria-label="Enable dark mode">dark_mode</span>
      <h6 id="toggleLabel">Dark mode</h6>
    </div>
    {% if g.user %}
      <div class="tab" id="account-menu">
          <div class="icon-with-badge">
            <span class="material-symbols-outlined">account_circle</span>
            <span class="credit-ticker">{{ g.user.credits_available }}</span>
            <h6>Account</h6>
          </div>
          <ul class="mobile-dropdown hidden" id="dropdown">
            <li class="mobile-dropdown-item account">
              <a href="{{ url_for('accounts.profile_view') }}" title="Profile">Profile</a>
            </li>
            <li class="mobile-dropdown-item account">
              <a href="{{ url_for('accounts.buy_credits_view') }}" title="Buy Credits">Buy Credits</a>
            </li>
            <li class="mobile-dropdown-item account">
              <a href="{{ url_for('accounts.view_binders_view') }}" title="Past purchases">Past Purchases</a>
            </li>
            <li class="mobile-dropdown-item account">
              <a href="{{ url_for('accounts.logout_view') }}" title="Log out">Logout</a>
            </li>
          </ul>
      </div>
    {% else %}
      <div class="tab last">
        <a href="{{ url_for('accounts.signup_view') }}">
          <span class="material-symbols-outlined" id="signup">login</span>
          <h6>Signup</h6>
        </a>
      </div>
    {% endif %}
  </nav>
</header>

src/prosepal/templates/core/privacy.html
{% extends 'base.html' %}

{% block title %}Privacy policy{% endblock %}
{% block content %}
  <h1>Privacy Policy for ProsePal</h1>
  <p><strong>Effective Date:</strong> January 25, 2024</p>

  <p>This privacy policy describes how ProsePal ("we" or "us") collects, uses, and shares personal information about you when you access our website, use our online services, or otherwise interact with us. Please read this privacy policy carefully.</p>

  <h2>Information We Collect</h2>
  <p>We only collect information that helps us provide services and products to you. The types of information we collect depends on how you use our services. The information we collect may include:</p>
  <ul>
      <li>Contact information such as your name, email address, postal address, and phone number if you provide it to us.</li>
      <li>Billing information such as your payment method (valid credit card number, type, expiration date or other financial information) if you make purchases from us.</li>
      <li>Technical information such as your IP address, browser type, operating system, referring URLs, device information, and other information about how you interact with our website.</li>
      <li>Usage information about your use of our website, products, and services.</li>
      <li>Communications you send to us, such as feedback and questions.</li>
      <li>Demographic information and other information provided by you that does not reveal your identity or contact information.</li>
  </ul>

  <h2>Analytics Information</h2>
  <p>We use Google Analytics to collect and analyze information about the use of our website. Google Analytics gathers data such as your IP address, browser type, device information, and website interactions. This information helps us understand how visitors use our site, improve user experience, and make informed decisions about our content and design.</p>

  <h2>How We Use Information</h2>
  <p>We use the information we collect for purposes such as:</p>
  <ul>
      <li>Providing, operating, and improving our website, products, and services.</li>
      <li>Processing orders and delivering products and services you request.</li>
      <li>Communicating with you about your account, orders, and services.</li>
      <li>Understanding how our users interact with our website so we can improve our website and services.</li>
      <li>Processing applications if you apply for a job with us.</li>
      <li>Detecting, preventing, and responding to fraud, intellectual property infringement, violations of our terms and policies, violations of law, or other misuse of our products and services.</li>
  </ul>

  <h2>How We Share Information</h2>
  <p>We do not sell or rent your personal information to third parties. We only share your information in the following circumstances:</p>
  <ul>
      <li>With third party service providers that perform services on our behalf, but these service providers are prohibited from using your information for any other purpose.</li>
      <li>To comply with legal obligations and enforce our terms and conditions.</li>
      <li>In connection with the sale, assignment, merger or other transfer of the business of this website to which the information relates.</li>
      <li>For any other purpose disclosed at the time you provide your information or with your consent.</li>
  </ul>

  <h2>Your Choices</h2>
  <p>You can request to review, correct, delete, or limit our use of your personal information. You can also opt out of marketing communications we send you. To make privacy requests, contact us at <a href="/contact-us">[insert contact info]</a>.</p>

  <h2>Data Storage and Retention</h2>
  <p>We retain your personal information only as long as necessary to provide you our services, or as described in any agreements you have with us. We do not retain any information from free tools longer than it takes to perform the requested tasks. For paid tools, we keep your data for as long as your account is active, or as needed to comply with our legal obligations, resolve disputes, enforce our agreements, and protect ProsePal, unless asked to remove your intellectual property.</p>

  <h2>Security of Your Information</h2>
  <p>We take reasonable administrative, physical and electronic measures designed to protect the security of the information that we collect from or about you. Please be aware that no security measures are perfect or impenetrable. We cannot guarantee the security of our database, nor can we guarantee that the information you supply will not be intercepted while being transmitted to and from us over the Internet.</p>

  <h2>Children's Privacy</h2>
  <p>Our website is not directed to children under the age of 13. We do not knowingly collect personal information from children under 13 without parental consent. If we learn that a child under 13 has provided us with personal information, we will delete it in accordance with applicable law. Contact us if you believe that a child under 13 has provided us with personal information.</p>

  <h2>Changes to This Privacy Policy</h2>
  <p>We may revise this privacy policy from time to time. If we make material changes to this policy, we will notify you of those changes by posting them on our website or sending you an email or other notification, and we will update the effective date above. We encourage you to review this privacy policy periodically to stay up to date about our privacy practices.</p>

  <h2>Contact Us</h2>
  <p>If you have any questions about this privacy policy or our privacy practices, please <a href="/contact-us">contact us</a>.</p>
{% endblock content %}

src/prosepal/templates/core/terms.html
{% extends 'base.html' %}

{% block title %}Terms and Conditions{% endblock %}
{% block content %}
  <h1>Terms and Conditions</h1>
  <p><span style="font-style: italic">Last Updated: 2024 January 25</span></p>
  <h2>1. Acceptance of Terms</h2>
  <p>Welcome to ProsePal. By accessing or using our website and services, you agree to be bound by these Terms and Conditions (the “Terms”). If you do not agree to these Terms, you may not use our services.</p>
  <h2>2. Services Provided</h2>
  <p>ProsePal offers AI-powered tools to assist authors with analytics, fine-tuning, writing, and related tasks for their manuscripts and literary works.</p>
  <h2>3. User Responsibilities</h2>
  <p>(a) Content Ownership: Users must only upload or input data, manuscripts, and writing that they own or have explicit permission to use. The use of copyrighted, plagiarized, or third-party content without proper authorization is strictly prohibited.</p>
  <p>(b) Data Security: Users are responsible for maintaining the confidentiality of their account and data and are liable for all activities under their account.</p>
  <p>(c) Acceptable Use: Users must not use our services for any illegal or unauthorized purpose.</p>
  <h2>4. Intellectual Property Rights</h2>
  <p>(a) User Content: Users retain all rights to their original content uploaded or created through our services.</p>
  <p>(b) AI-Generated Content: Content generated by the AI that is derivative of user-provided data is the intellectual property of the user. ProsePal makes no claim over such AI-generated content.</p>
  <p>(c) Service Content: All intellectual property rights in the underlying code, software, and algorithms of our service belong to ProsePal. The service code will be available under an <a href="https://opensource.org/license/mit/" rel="noopener" target="_blank" title="MIT License">open-source MIT license</a>, which governs its use and distribution.</p>
  <h2>5. Privacy Policy</h2>
  <p>User data and information are handled in accordance with our Privacy Policy, which can be found at <a href="/privacy" target="-blank">https://prosepal.io/privacy</a>.</p>
  <h2>6. Limitation of Liability</h2>
  <p>ProsePal shall not be liable for any direct, indirect, incidental, special, or consequential damages resulting from the use or inability to use our services.</p>
  <h2>7. Amendments to Terms</h2>
  <p>We reserve the right to modify or replace these Terms at any time. Your continued use of our services after any changes indicates your acceptance of the new Terms.</p>
  <h2>8. Termination</h2>
  <p>We may terminate or suspend access to our services immediately, without prior notice or liability, for any reason whatsoever, including without limitation if you breach the Terms.</p>
  <h2>9. Governing Law</h2>
  <p>These Terms shall be governed and construed in accordance with the laws of the state of Colorado and the United States, without regard to its conflict of law provisions.</p>
  <h2>10. Contact Information</h2>
  <p>For any questions about these Terms, please <a href="/contact-us" target="_blank">contact us</a>.</p>
{% endblock content %}

src/prosepal/templates/core/updates.html
{% if update_message %}
  <div class="update-modal shown">
    {% for message in update_message %}
      <p class="update-info">{{ message.message }} from {{ message.start_time }} to {{ message.end_time }}</p>
      <div id="close"><span class="material-symbols-outlined">close</span></div>
    {% endfor %}
  </div>
  <script src="{{ url_for('static', filename='js/updates.js')}}"></script>
{% endif %}